### ISSUE TITLE
Update namespaces to new syntax

### ISSUE THREAD

**Issue by reecerussell** [reecerussell/http-moq#23]
A small issue to update the namespace definitions to use the new unindented versions.

**From:**
```csharp
namespace HttpMoq
{
    // ...
}
```

**To:**
```csharp
namespace HttpMoq;

// ...
```

This is a good first issue and should be relatively pain-free. One thing to look out for is if any .NET versions need to be updated/supported/unsupported to use this. I believe it's just a C# version change.

**Comment by Joseph-Egan** [comment]
I can take this one! I'll have to update the test project to .NET 6.

**Comment by reecerussell** [comment]
Hey @Joseph-Egan, thanks for getting involved - sorry I have just seen this!
